//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardySoft.UI.BatchImageProcessor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HardySoft.UI.BatchImageProcessor.Resources.LanguageContent", typeof(LanguageContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://code.google.com/p/batch-image-watermark-processor/.
        /// </summary>
        internal static string ApplicationUrl {
            get {
                return ResourceManager.GetString("ApplicationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check New Version.
        /// </summary>
        internal static string Button_CheckVersion {
            get {
                return ResourceManager.GetString("Button_CheckVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Button_Font {
            get {
                return ResourceManager.GetString("Button_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Command_About {
            get {
                return ResourceManager.GetString("Command_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Command_Exit {
            get {
                return ResourceManager.GetString("Command_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        internal static string Command_Make {
            get {
                return ResourceManager.GetString("Command_Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string Command_NewProject {
            get {
                return ResourceManager.GetString("Command_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        internal static string Command_OpenProject {
            get {
                return ResourceManager.GetString("Command_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string Command_Preference {
            get {
                return ResourceManager.GetString("Command_Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project As.
        /// </summary>
        internal static string Command_SaveAs {
            get {
                return ResourceManager.GetString("Command_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        internal static string Command_SaveProject {
            get {
                return ResourceManager.GetString("Command_SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Command_Stop {
            get {
                return ResourceManager.GetString("Command_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture Priority.
        /// </summary>
        internal static string Enum_AperturePriority {
            get {
                return ResourceManager.GetString("Enum_AperturePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Center.
        /// </summary>
        internal static string Enum_BottomCenter {
            get {
                return ResourceManager.GetString("Enum_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        internal static string Enum_BottomLeft {
            get {
                return ResourceManager.GetString("Enum_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        internal static string Enum_BottomRight {
            get {
                return ResourceManager.GetString("Enum_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy Weather.
        /// </summary>
        internal static string Enum_CloudyWeather {
            get {
                return ResourceManager.GetString("Enum_CloudyWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool White Fluorescent.
        /// </summary>
        internal static string Enum_CoolWhiteFluorescent {
            get {
                return ResourceManager.GetString("Enum_CoolWhiteFluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daylight.
        /// </summary>
        internal static string Enum_Daylight {
            get {
                return ResourceManager.GetString("Enum_Daylight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daylight Fluorescent.
        /// </summary>
        internal static string Enum_DaylightFluorescent {
            get {
                return ResourceManager.GetString("Enum_DaylightFluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day White Fluorescent.
        /// </summary>
        internal static string Enum_DayWhiteFluorescent {
            get {
                return ResourceManager.GetString("Enum_DayWhiteFluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Weather.
        /// </summary>
        internal static string Enum_FineWeather {
            get {
                return ResourceManager.GetString("Enum_FineWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        internal static string Enum_Flash {
            get {
                return ResourceManager.GetString("Enum_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Did Not Fire.
        /// </summary>
        internal static string Enum_FlashDidNotFire {
            get {
                return ResourceManager.GetString("Enum_FlashDidNotFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Fired.
        /// </summary>
        internal static string Enum_FlashFired {
            get {
                return ResourceManager.GetString("Enum_FlashFired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluorescent.
        /// </summary>
        internal static string Enum_Fluorescent {
            get {
                return ResourceManager.GetString("Enum_Fluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Enum_Height {
            get {
                return ResourceManager.GetString("Enum_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Speed Mode.
        /// </summary>
        internal static string Enum_HighSpeedMode {
            get {
                return ResourceManager.GetString("Enum_HighSpeedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO Studio Tungsten.
        /// </summary>
        internal static string Enum_ISOStudioTungsten {
            get {
                return ResourceManager.GetString("Enum_ISOStudioTungsten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape Mode.
        /// </summary>
        internal static string Enum_LandscapeMode {
            get {
                return ResourceManager.GetString("Enum_LandscapeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Side.
        /// </summary>
        internal static string Enum_LongSide {
            get {
                return ResourceManager.GetString("Enum_LongSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Case.
        /// </summary>
        internal static string Enum_LowerCase {
            get {
                return ResourceManager.GetString("Enum_LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Speed Mode.
        /// </summary>
        internal static string Enum_LowSpeedMode {
            get {
                return ResourceManager.GetString("Enum_LowSpeedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Enum_Manual {
            get {
                return ResourceManager.GetString("Enum_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Center.
        /// </summary>
        internal static string Enum_MiddleCenter {
            get {
                return ResourceManager.GetString("Enum_MiddleCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Left.
        /// </summary>
        internal static string Enum_MiddleLeft {
            get {
                return ResourceManager.GetString("Enum_MiddleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Right.
        /// </summary>
        internal static string Enum_MiddleRight {
            get {
                return ResourceManager.GetString("Enum_MiddleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Enum_None {
            get {
                return ResourceManager.GetString("Enum_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Program.
        /// </summary>
        internal static string Enum_NormalProgram {
            get {
                return ResourceManager.GetString("Enum_NormalProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Enum_Other {
            get {
                return ResourceManager.GetString("Enum_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait Mode.
        /// </summary>
        internal static string Enum_PortraitMode {
            get {
                return ResourceManager.GetString("Enum_PortraitMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shade.
        /// </summary>
        internal static string Enum_Shade {
            get {
                return ResourceManager.GetString("Enum_Shade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter Priority.
        /// </summary>
        internal static string Enum_ShutterPriority {
            get {
                return ResourceManager.GetString("Enum_ShutterPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Light A.
        /// </summary>
        internal static string Enum_StandardLightA {
            get {
                return ResourceManager.GetString("Enum_StandardLightA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Light B.
        /// </summary>
        internal static string Enum_StandardLightB {
            get {
                return ResourceManager.GetString("Enum_StandardLightB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Light C.
        /// </summary>
        internal static string Enum_StandardLightC {
            get {
                return ResourceManager.GetString("Enum_StandardLightC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Center.
        /// </summary>
        internal static string Enum_TopCenter {
            get {
                return ResourceManager.GetString("Enum_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        internal static string Enum_TopLeft {
            get {
                return ResourceManager.GetString("Enum_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        internal static string Enum_TopRight {
            get {
                return ResourceManager.GetString("Enum_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tungsten.
        /// </summary>
        internal static string Enum_Tungsten {
            get {
                return ResourceManager.GetString("Enum_Tungsten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncalibrated.
        /// </summary>
        internal static string Enum_Uncalibrated {
            get {
                return ResourceManager.GetString("Enum_Uncalibrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Enum_Unknown {
            get {
                return ResourceManager.GetString("Enum_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown.
        /// </summary>
        internal static string Enum_Unkown {
            get {
                return ResourceManager.GetString("Enum_Unkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Case.
        /// </summary>
        internal static string Enum_UpperCase {
            get {
                return ResourceManager.GetString("Enum_UpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Fluorescent.
        /// </summary>
        internal static string Enum_WhiteFluorescent {
            get {
                return ResourceManager.GetString("Enum_WhiteFluorescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Enum_Width {
            get {
                return ResourceManager.GetString("Enum_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Image Process Project Files.
        /// </summary>
        internal static string Label_AllProjects {
            get {
                return ResourceManager.GetString("Label_AllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported Images Files.
        /// </summary>
        internal static string Label_AllSupportedImagesFiles {
            get {
                return ResourceManager.GetString("Label_AllSupportedImagesFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        internal static string Label_Aperture {
            get {
                return ResourceManager.GetString("Label_Aperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Skin.
        /// </summary>
        internal static string Label_ApplicationSkin {
            get {
                return ResourceManager.GetString("Label_ApplicationSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        internal static string Label_Assembly {
            get {
                return ResourceManager.GetString("Label_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Label_Author {
            get {
                return ResourceManager.GetString("Label_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string Label_BackgroundColor {
            get {
                return ResourceManager.GetString("Label_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Rename.
        /// </summary>
        internal static string Label_BatchRename {
            get {
                return ResourceManager.GetString("Label_BatchRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Border Color.
        /// </summary>
        internal static string Label_BorderColor {
            get {
                return ResourceManager.GetString("Label_BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Settings.
        /// </summary>
        internal static string Label_BorderSettings {
            get {
                return ResourceManager.GetString("Label_BorderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Border Width.
        /// </summary>
        internal static string Label_BorderWidth {
            get {
                return ResourceManager.GetString("Label_BorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Label_Camera {
            get {
                return ResourceManager.GetString("Label_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Watermark Image.
        /// </summary>
        internal static string Label_ChooseWatermarkImage {
            get {
                return ResourceManager.GetString("Label_ChooseWatermarkImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Code:.
        /// </summary>
        internal static string Label_ColorCode {
            get {
                return ResourceManager.GetString("Label_ColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Representation.
        /// </summary>
        internal static string Label_ColorRepresentation {
            get {
                return ResourceManager.GetString("Label_ColorRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Label_Copyright {
            get {
                return ResourceManager.GetString("Label_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Software.
        /// </summary>
        internal static string Label_CreationSoftware {
            get {
                return ResourceManager.GetString("Label_CreationSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Taken.
        /// </summary>
        internal static string Label_DateTaken {
            get {
                return ResourceManager.GetString("Label_DateTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Destination Folder to Save Processed Images.
        /// </summary>
        internal static string Label_DestFolder {
            get {
                return ResourceManager.GetString("Label_DestFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Shadow Color.
        /// </summary>
        internal static string Label_DropShadowColor {
            get {
                return ResourceManager.GetString("Label_DropShadowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Shadow Settings.
        /// </summary>
        internal static string Label_DropShadowSettings {
            get {
                return ResourceManager.GetString("Label_DropShadowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Batch Rename.
        /// </summary>
        internal static string Label_EnableBatchRename {
            get {
                return ResourceManager.GetString("Label_EnableBatchRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Label_Error {
            get {
                return ResourceManager.GetString("Label_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Compensation.
        /// </summary>
        internal static string Label_ExposureCompensation {
            get {
                return ResourceManager.GetString("Label_ExposureCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Mode.
        /// </summary>
        internal static string Label_ExposureMode {
            get {
                return ResourceManager.GetString("Label_ExposureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Time.
        /// </summary>
        internal static string Label_ExposureTime {
            get {
                return ResourceManager.GetString("Label_ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Mode.
        /// </summary>
        internal static string Label_FlashMode {
            get {
                return ResourceManager.GetString("Label_FlashMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal Length.
        /// </summary>
        internal static string Label_FocalLength {
            get {
                return ResourceManager.GetString("Label_FocalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Thumbnail.
        /// </summary>
        internal static string Label_GenerateThumbnail {
            get {
                return ResourceManager.GetString("Label_GenerateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Label_Height {
            get {
                return ResourceManager.GetString("Label_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal Notation.
        /// </summary>
        internal static string Label_Hex {
            get {
                return ResourceManager.GetString("Label_Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Resolution.
        /// </summary>
        internal static string Label_HorizontalResolution {
            get {
                return ResourceManager.GetString("Label_HorizontalResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Effect.
        /// </summary>
        internal static string Label_ImageEffect {
            get {
                return ResourceManager.GetString("Label_ImageEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File List.
        /// </summary>
        internal static string Label_ImageFileList {
            get {
                return ResourceManager.GetString("Label_ImageFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File Name.
        /// </summary>
        internal static string Label_ImageFileName {
            get {
                return ResourceManager.GetString("Label_ImageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO Speed.
        /// </summary>
        internal static string Label_ISOSpeed {
            get {
                return ResourceManager.GetString("Label_ISOSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPG Compression Ratio.
        /// </summary>
        internal static string Label_JPGCompressionRatio {
            get {
                return ResourceManager.GetString("Label_JPGCompressionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep EXIF.
        /// </summary>
        internal static string Label_KeepEXIF {
            get {
                return ResourceManager.GetString("Label_KeepEXIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version.
        /// </summary>
        internal static string Label_LatestVersion {
            get {
                return ResourceManager.GetString("Label_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Label_Manufacturer {
            get {
                return ResourceManager.GetString("Label_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Version.
        /// </summary>
        internal static string Label_MyVersion {
            get {
                return ResourceManager.GetString("Label_MyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Padding.
        /// </summary>
        internal static string Label_NumberPadding {
            get {
                return ResourceManager.GetString("Label_NumberPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Label_Opacity {
            get {
                return ResourceManager.GetString("Label_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Watermark Image.
        /// </summary>
        internal static string Label_OpenWatermarkImage {
            get {
                return ResourceManager.GetString("Label_OpenWatermarkImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouput Directory.
        /// </summary>
        internal static string Label_OuputDirectory {
            get {
                return ResourceManager.GetString("Label_OuputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File Name Case.
        /// </summary>
        internal static string Label_OutputFileNameCase {
            get {
                return ResourceManager.GetString("Label_OutputFileNameCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File Name Prefix.
        /// </summary>
        internal static string Label_OutputFileNamePrefix {
            get {
                return ResourceManager.GetString("Label_OutputFileNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File Name Suffix.
        /// </summary>
        internal static string Label_OutputFileNameSuffix {
            get {
                return ResourceManager.GetString("Label_OutputFileNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Settings.
        /// </summary>
        internal static string Label_PictureSettings {
            get {
                return ResourceManager.GetString("Label_PictureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  pixel(s).
        /// </summary>
        internal static string Label_Pixel {
            get {
                return ResourceManager.GetString("Label_Pixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string Label_ProductName {
            get {
                return ResourceManager.GetString("Label_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product URL.
        /// </summary>
        internal static string Label_ProductURL {
            get {
                return ResourceManager.GetString("Label_ProductURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string Label_Selected {
            get {
                return ResourceManager.GetString("Label_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Color.
        /// </summary>
        internal static string Label_SelectedColor {
            get {
                return ResourceManager.GetString("Label_SelectedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Depth.
        /// </summary>
        internal static string Label_ShadowDepth {
            get {
                return ResourceManager.GetString("Label_ShadowDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Location.
        /// </summary>
        internal static string Label_ShadowLocation {
            get {
                return ResourceManager.GetString("Label_ShadowLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink Image.
        /// </summary>
        internal static string Label_ShrinkImage {
            get {
                return ResourceManager.GetString("Label_ShrinkImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink Image To.
        /// </summary>
        internal static string Label_ShrinkImageTo {
            get {
                return ResourceManager.GetString("Label_ShrinkImageTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink Option.
        /// </summary>
        internal static string Label_ShrinkOption {
            get {
                return ResourceManager.GetString("Label_ShrinkOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Directory.
        /// </summary>
        internal static string Label_SourceDirectory {
            get {
                return ResourceManager.GetString("Label_SourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder with Images to Process.
        /// </summary>
        internal static string Label_SourceFolder {
            get {
                return ResourceManager.GetString("Label_SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Number.
        /// </summary>
        internal static string Label_StartNumber {
            get {
                return ResourceManager.GetString("Label_StartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        internal static string Label_SysInfo {
            get {
                return ResourceManager.GetString("Label_SysInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Thread Number.
        /// </summary>
        internal static string Label_ThreadNumber {
            get {
                return ResourceManager.GetString("Label_ThreadNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string Label_Thumbnail {
            get {
                return ResourceManager.GetString("Label_Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail File Name Prefix.
        /// </summary>
        internal static string Label_ThumbnailFileNamePrefix {
            get {
                return ResourceManager.GetString("Label_ThumbnailFileNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail File Name Suffix.
        /// </summary>
        internal static string Label_ThumbnailFileNameSuffix {
            get {
                return ResourceManager.GetString("Label_ThumbnailFileNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Size.
        /// </summary>
        internal static string Label_ThumbnailSize {
            get {
                return ResourceManager.GetString("Label_ThumbnailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Project.
        /// </summary>
        internal static string Label_UnsavedProject {
            get {
                return ResourceManager.GetString("Label_UnsavedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.hsbip.
        /// </summary>
        internal static string Label_UntitledProjectName {
            get {
                return ResourceManager.GetString("Label_UntitledProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Resolution.
        /// </summary>
        internal static string Label_VerticalResolution {
            get {
                return ResourceManager.GetString("Label_VerticalResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Image.
        /// </summary>
        internal static string Label_WatermarkImage {
            get {
                return ResourceManager.GetString("Label_WatermarkImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Image Position.
        /// </summary>
        internal static string Label_WatermarkImagePosition {
            get {
                return ResourceManager.GetString("Label_WatermarkImagePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Image.
        /// </summary>
        internal static string Label_WatermarkImagePreview {
            get {
                return ResourceManager.GetString("Label_WatermarkImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Text.
        /// </summary>
        internal static string Label_WatermarkText {
            get {
                return ResourceManager.GetString("Label_WatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Text Font.
        /// </summary>
        internal static string Label_WatermarkTextFont {
            get {
                return ResourceManager.GetString("Label_WatermarkTextFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Text Position.
        /// </summary>
        internal static string Label_WatermarkTextPosition {
            get {
                return ResourceManager.GetString("Label_WatermarkTextPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Balance Mode.
        /// </summary>
        internal static string Label_WhiteBalanceMode {
            get {
                return ResourceManager.GetString("Label_WhiteBalanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Label_Width {
            get {
                return ResourceManager.GetString("Label_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Process.
        /// </summary>
        internal static string Menu_Process {
            get {
                return ResourceManager.GetString("Menu_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version {0} available, please visit application homepage to download..
        /// </summary>
        internal static string Message_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Message_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version..
        /// </summary>
        internal static string Message_NoNewVersion {
            get {
                return ResourceManager.GetString("Message_NoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save project setting first?.
        /// </summary>
        internal static string Message_SavePrompt {
            get {
                return ResourceManager.GetString("Message_SavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check new version at the moment, please make sure you have active Internet connection and try again later..
        /// </summary>
        internal static string Message_UnableToCheckVersion {
            get {
                return ResourceManager.GetString("Message_UnableToCheckVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibri, Verdana.
        /// </summary>
        internal static string Style_AboutLabel {
            get {
                return ResourceManager.GetString("Style_AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibri, Verdana.
        /// </summary>
        internal static string Style_AboutText {
            get {
                return ResourceManager.GetString("Style_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdana.
        /// </summary>
        internal static string Style_ButtonFont {
            get {
                return ResourceManager.GetString("Style_ButtonFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdana.
        /// </summary>
        internal static string Style_ConfigLabel {
            get {
                return ResourceManager.GetString("Style_ConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibri, Tahoma, Arial.
        /// </summary>
        internal static string Style_ConfigTextBox {
            get {
                return ResourceManager.GetString("Style_ConfigTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdana.
        /// </summary>
        internal static string Style_MenuFont {
            get {
                return ResourceManager.GetString("Style_MenuFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdana.
        /// </summary>
        internal static string Style_ToolbarText {
            get {
                return ResourceManager.GetString("Style_ToolbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdana.
        /// </summary>
        internal static string Style_WindowFooterFont {
            get {
                return ResourceManager.GetString("Style_WindowFooterFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdana.
        /// </summary>
        internal static string Style_WindowTitleFont {
            get {
                return ResourceManager.GetString("Style_WindowTitleFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Selection.
        /// </summary>
        internal static string TabHeader_DirectorySelection {
            get {
                return ResourceManager.GetString("TabHeader_DirectorySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Settings.
        /// </summary>
        internal static string TabHeader_OutputSettings {
            get {
                return ResourceManager.GetString("TabHeader_OutputSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Settings.
        /// </summary>
        internal static string TabHeader_ProcessSettings {
            get {
                return ResourceManager.GetString("TabHeader_ProcessSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Settings.
        /// </summary>
        internal static string TabHeader_WatermarkSetting {
            get {
                return ResourceManager.GetString("TabHeader_WatermarkSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpg compression ratio must be between 0 and 100..
        /// </summary>
        internal static string Validation_JpgCompressionRatio {
            get {
                return ResourceManager.GetString("Validation_JpgCompressionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an output directory to proceed..
        /// </summary>
        internal static string Validation_ReqDestDirectory {
            get {
                return ResourceManager.GetString("Validation_ReqDestDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a source directory with image(s) to proceed..
        /// </summary>
        internal static string Validation_ReqSouceDirectory {
            get {
                return ResourceManager.GetString("Validation_ReqSouceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string WindowTitle_About {
            get {
                return ResourceManager.GetString("WindowTitle_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version.
        /// </summary>
        internal static string WindowTitle_ApplicationVersion {
            get {
                return ResourceManager.GetString("WindowTitle_ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Color.
        /// </summary>
        internal static string WindowTitle_ColorPicker {
            get {
                return ResourceManager.GetString("WindowTitle_ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Turtle Image Processor.
        /// </summary>
        internal static string WindowTitle_Main {
            get {
                return ResourceManager.GetString("WindowTitle_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string WindowTitle_Preference {
            get {
                return ResourceManager.GetString("WindowTitle_Preference", resourceCulture);
            }
        }
    }
}
