//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardySoft.UI.BatchImageProcessor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HardySoft.UI.BatchImageProcessor.Resources.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Center.
        /// </summary>
        internal static string BottomCenter {
            get {
                return ResourceManager.GetString("BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        internal static string BottomLeft {
            get {
                return ResourceManager.GetString("BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        internal static string BottomRight {
            get {
                return ResourceManager.GetString("BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Center.
        /// </summary>
        internal static string MiddleCenter {
            get {
                return ResourceManager.GetString("MiddleCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Left.
        /// </summary>
        internal static string MiddleLeft {
            get {
                return ResourceManager.GetString("MiddleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Right.
        /// </summary>
        internal static string MiddleRight {
            get {
                return ResourceManager.GetString("MiddleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Center.
        /// </summary>
        internal static string TopCenter {
            get {
                return ResourceManager.GetString("TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        internal static string TopLeft {
            get {
                return ResourceManager.GetString("TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        internal static string TopRight {
            get {
                return ResourceManager.GetString("TopRight", resourceCulture);
            }
        }
    }
}
